const mongoose=require("mongoose");
const ParentSchema=mongoose.Schema({
    Name:{
        type:String
    },
    email:{
        type:String,
        require:true
    },
    password:{
        type:String,
        require:true
    },
    Student_name:{
      type:String
    },
    student_id:{
        type:String
    },
    phonenumber:{
        type:Number
    },
    address:{
        type:String
    },
    pincode:{
        type:String
    }
},
{
    Timestamp:true
},
)
module.exports=mongoose.model("Parents",ParentSchema);